import type { Article } from '../../types/index.ts';

// 文件意图：维护《The Altair 8800 and the Personal Computer Revolution: DIY Computing Takes Off》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00026 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00026',
  slug: 'the-altair-8800-and-the-personal-computer-revolution-diy-computing-takes-off',
  title: 'The Altair 8800 and the Personal Computer Revolution: DIY Computing Takes Off',
  subtitle: 'How a hobbyist kit sparked the modern PC era',
  summary: 'The Altair 8800 turned bedroom tinkering into a global industry, launching the personal computer revolution.',
  category: 'technology',
  difficulty: 'intermediate',
  readingMinutes: 6,
  paragraphs: [
    `The story of modern computing often begins with a modest box of switches and lights that appeared on the cover of Popular Electronics in January 1975. Dubbed the Altair 8800, this machine was one of the first commercially available <span class="vocab" data-cn="微型计算机">microcomputer</span> kits, and its striking photograph sparked a wave of curiosity among engineers, students, and tinkerers across the United States. At a time when hobby electronics magazines were flourishing and affordable transistors made home projects feasible, the Altair captured the imagination of a generation eager to build their own digital devices.`,
    `At its heart lay Intel's newly released 8080 <span class="vocab" data-cn="中央处理器">CPU</span>, a powerful eight‑bit processor that could execute thousands of instructions per second. The front panel featured rows of toggle switches for inputting binary code and a bank of LEDs that displayed the machine’s internal state, turning programming into a hands‑on, almost theatrical experience. The 8080 ran at up to 2 MHz, could address a full 64 KB of memory, and was originally designed for calculators and other embedded applications.`,
    `The Altair was sold primarily as a <span class="vocab" data-cn="套件">kit</span>, meaning buyers received a box of circuit boards, wires, and components that they had to assemble themselves. This DIY approach forced users to confront the machine’s <span class="vocab" data-cn="固件">firmware</span>—a tiny read‑only memory that performed the initial power‑on self‑test—and gave them a deep understanding of how hardware and software interact. The base kit cost $439 at launch, and optional memory boards could raise the price to over $600, making it a serious investment for hobbyists. Builders often spent evenings with oscilloscopes and multimeters, learning to read schematics and debug faulty connections, experiences that forged a generation of hardware engineers.`,
    `The lack of ready‑made software was quickly addressed by two young programmers, Bill Gates and Paul Allen, who wrote a version of <span class="vocab" data-cn="基本语言">BASIC</span> for the Altair. Their product, Altair BASIC, became the first commercial success for what would later become Microsoft, demonstrating that even a hobbyist platform could support serious <span class="vocab" data-cn="软件">software</span> development. Because BASIC allowed users to write programs in an English‑like syntax, it lowered the barrier to entry dramatically; early versions were distributed on paper tape or cassette, and later loaded from floppy disks as the technology matured.`,
    `The Altair’s open nature attracted a growing community of <span class="vocab" data-cn="爱好者">hobbyist</span> engineers who met in garages, university labs, and later in the famous Homebrew Computer Club. They exchanged schematics, wrote custom expansions, and shared code on early bulletin board systems, laying the groundwork for what we now recognize as an open‑source culture—though the term itself would not be coined until decades later. Publications such as Byte, Creative Computing, and the Homebrew Computer Club newsletter printed schematics, user stories, and modification tips, turning the hobby into a vibrant subculture.`,
    `Beyond BASIC, the Altair became a testing ground for one of the earliest <span class="vocab" data-cn="操作系统">operating system</span> implementations. In 1974 Gary Kildall had already written <span class="vocab" data-cn="CP/M（微型计算机控制程序）">CP/M</span> (Control Program for Microcomputers) for Intel 8080‑based machines, and by the late 1970s several hobbyists adapted it to run on Altair clones, enabling disk‑based storage and multitasking capabilities that were unheard of in kit computers. The availability of CP/M demonstrated that a modest microcomputer could support sophisticated software, paving the way for business applications and influencing the design of later machines such as the IBM PC. When Microsoft later licensed CP/M‑compatible technology to IBM for its first PC, it laid the foundation for MS‑DOS, which dominated the personal computer market throughout the 1980s.`,
    `The momentum generated by the Altair did not stop at kits. Companies such as Apple, Commodore, and Tandy took inspiration from MITS’s design philosophy and produced fully assembled <span class="vocab" data-cn="个人计算机">personal computer</span> systems that could sit on a desk rather than a workbench. The Apple I was sold as a single board that users could plug into their own monitors and keyboards, while the Commodore PET integrated a monitor, keyboard, and cassette storage into one unit, and the Tandy TRS‑80 offered a ready‑to‑use system for under $1,000. By the early 1980s, the market had shifted from hobbyist construction to ready‑to‑use machines, but the spirit of hands‑on experimentation persisted.`,
    `Today’s <span class="vocab" data-cn="DIY 计算">DIY computing</span> movement—embodied by platforms like Raspberry Pi and Arduino—traces its lineage directly back to the Altair 8800. The original kit proved that powerful, programmable hardware could be affordable enough for individuals, a lesson that continues to empower creators around the world. Schools now use these low‑cost boards to teach programming and electronics, maker spaces host workshops where participants build everything from robots to IoT devices, and open‑hardware initiatives publish complete design files under permissive licenses, keeping alive the collaborative spirit that began in 1975.`,
  ],
  vocabulary: [
    { word: 'microcomputer', cn: '微型计算机' },
    { word: 'CPU', cn: '中央处理器' },
    { word: 'kit', cn: '套件' },
    { word: 'firmware', cn: '固件' },
    { word: 'BASIC', cn: '基本语言' },
    { word: 'software', cn: '软件' },
    { word: 'hobbyist', cn: '爱好者' },
    { word: 'operating system', cn: '操作系统' },
    { word: 'CP/M', cn: 'CP/M（微型计算机控制程序）' },
    { word: 'personal computer', cn: '个人计算机' },
    { word: 'DIY computing', cn: 'DIY 计算' },
  ],
};

export default article;
