import type { Article } from '../../types/index.ts';

// 文件意图：维护《Rachel Carson and Silent Spring: The Dawn of the Environmental Movement》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00031 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00031',
  slug: 'rachel-carson-and-silent-spring-the-dawn-of-the-environmental-movement',
  title: 'Rachel Carson and Silent Spring: The Dawn of the Environmental Movement',
  subtitle: 'How a single book sparked a global environmental awakening',
  summary: "Explore how Rachel Carson's Silent Spring ignited the modern environmental movement.",
  category: 'science',
  difficulty: 'intermediate',
  readingMinutes: 6,
  paragraphs: [
    `Rachel Carson was born in 1907 on a farm in Pennsylvania, a setting that nurtured her lifelong fascination with nature. After earning a master’s degree in zoology, she joined the U.S. Fish and Wildlife Service as a writer and later became a respected marine biologist. Her early books, such as The Sea Around Us (1951) and The Edge of the Sea (1955), combined lyrical prose with rigorous scientific observation, introducing millions of readers to the wonders of the ocean. These works also laid the groundwork for her most influential project by teaching her how to translate complex data into compelling narratives that could reach a broad public, helping people appreciate the ocean as an interconnected <span class="vocab" data-cn="生态系统">ecosystem</span>.`,
    `In the post‑World war II era, governments and farmers embraced synthetic chemicals with unprecedented enthusiasm. The most celebrated of these was DDT, a powerful <span class="vocab" data-cn="农药">pesticide</span> that promised to eradicate insects that threatened crops and disease vectors alike. Initially hailed as a miracle solution, DDT’s widespread application soon revealed unintended consequences: it accumulated in soil, water, and the bodies of non‑target species. By the late 1950s, scientists began reporting alarming declines in bird populations, particularly raptors whose eggshells were becoming dangerously thin. These observations hinted at deeper ecological disruptions that ordinary citizens could not see but would soon feel the impact of.`,
    `Carson embarked on a painstaking investigation to uncover the hidden pathways through which chemicals moved through nature. She consulted peer‑reviewed studies, interviewed field biologists, and examined government reports, weaving together a narrative that highlighted the process of <span class="vocab" data-cn="生物累积">bioaccumulation</span>. This phenomenon describes how toxic substances concentrate in organisms at each step of the food chain, ultimately reaching levels that can be lethal to top predators. In Silent Spring, Carson illustrated this with vivid examples: a single grain of DDT could travel from a sprayed field to a fish, then to a heron, and finally to an eagle, where it would impair reproduction. By making these connections clear, she showed how human actions could destabilize entire <span class="vocab" data-cn="生态系统">ecosystem</span>s.`,
    `When Silent Spring was published in September 1962, its stark warnings sparked a firestorm of public debate. Newspapers ran excerpts, radio programs invited Carson to speak, and the chemical industry launched an aggressive campaign to discredit her findings. Yet the book resonated with a growing audience that was increasingly aware of environmental degradation. Readers responded with letters of concern, petitions, and grassroots meetings, turning scientific evidence into powerful <span class="vocab" data-cn="倡导">advocacy</span>. Carson’s eloquent prose also emphasized the importance of maintaining <span class="vocab" data-cn="生态平衡">ecological balance</span>, arguing that humanity could not continue to dominate nature without paying a steep ecological price.`,
    `The outcry generated by Silent Spring helped catalyze concrete political action. In the United States, Congress began holding hearings on pesticide regulation, leading to the passage of the Federal Insecticide, Fungicide, and Rodenticide Act amendments that required stricter safety testing. Most notably, the book’s influence contributed to the establishment of the Environmental Protection Agency (EPA) in 1970, a federal body tasked with protecting human health and the environment. Within a few years, the EPA banned DDT for agricultural use, marking one of the first major victories of modern <span class="vocab" data-cn="立法">legislation</span> driven by scientific <span class="vocab" data-cn="倡导">advocacy</span>.`,
    `Beyond the United States, Silent Spring ignited a global environmental consciousness. The book inspired the first Earth Day in April 1970, an event that drew millions of participants and signaled the rise of a transnational movement against pollution, habitat loss, and climate change. New non‑governmental organizations such as Greenpeace emerged, using direct action to challenge corporate practices deemed harmful. Carson’s work also underscored the role of <span class="vocab" data-cn="人类活动的">anthropogenic</span> forces in reshaping the planet, prompting scientists and policymakers alike to prioritize <span class="vocab" data-cn="自然保护">conservation</span> strategies that balance development with ecological stewardship.`,
    `Today, Rachel Carson’s legacy endures as a blueprint for how rigorous science can inform public discourse and policy. While the challenges of climate change, plastic pollution, and biodiversity loss have eclipsed the specific issue of DDT, the core message of Silent Spring remains relevant: unchecked chemical use threatens the health of all living beings. Modern environmental advocates continue to draw on Carson’s example, crafting clear, evidence‑based narratives that aim to mobilize citizens worldwide. In this way, Silent Spring lives on not only as a historic text but also as an active catalyst for ongoing <span class="vocab" data-cn="自然保护">conservation</span> efforts.`,
  ],
  vocabulary: [
    { word: 'ecosystem', cn: '生态系统' },
    { word: 'pesticide', cn: '农药' },
    { word: 'bioaccumulation', cn: '生物累积' },
    { word: 'advocacy', cn: '倡导' },
    { word: 'ecological balance', cn: '生态平衡' },
    { word: 'legislation', cn: '立法' },
    { word: 'anthropogenic', cn: '人类活动的' },
    { word: 'conservation', cn: '自然保护' },
  ],
};

export default article;
