import type { Article } from '../../types/index.ts';

// 文件意图：维护《The Mystery of the Taos Hum: An Unexplained Low‑Frequency Sound That Baffled Scientists》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00098 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00098',
  slug: 'the-mystery-of-the-taos-hum-an-unexplained-low-frequency-sound-that-baffled-scientists',
  title: 'The Mystery of the Taos Hum: An Unexplained Low‑Frequency Sound That Baffled Scientists',
  subtitle: 'A puzzling acoustic phenomenon that still defies consensus.',
  summary: 'Explore how a faint, low‑frequency hum in Taos sparked worldwide curiosity and scientific debate.',
  category: 'science',
  difficulty: 'intermediate',
  readingMinutes: 5,
  paragraphs: [
    `It was a crisp autumn evening in 1990 when a handful of residents in the small New Mexico town of Taos began to notice an odd, persistent drone that seemed to linger just beneath the threshold of hearing. The sound, described as a low‑frequency hum akin to “the distant rumble of a diesel engine,” was not audible to everyone, yet those who could hear it reported sleepless nights and a lingering sense of unease. This first wave of complaints set off a chain reaction that would eventually draw the attention of acousticians, neurologists, and even geophysicists from across the United States.`,
    `Scientists arrived armed with portable sound meters and began a systematic <span class="vocab" data-cn="声谱分析">spectral analysis</span> of the ambient environment. Their instruments recorded the background noise levels at various frequencies, hoping to isolate a distinct peak that could be linked to the reported hum. Surprisingly, most recordings failed to capture any anomalous signal above the normal <span class="vocab" data-cn="环境噪声">ambient noise</span> floor, leading researchers to suspect that the phenomenon might be more psychological than physical. This hypothesis sparked a debate about the role of <span class="vocab" data-cn="心理生理学">psychophysiology</span> in auditory perception.`,
    `One prominent theory suggested that the hum could be a form of <span class="vocab" data-cn="次声">infrasound</span>, sound waves below 20 Hz that are typically felt rather than heard. Infrasound can be generated by natural sources such as wind interacting with topography, or by human activities like large‑scale ventilation systems. To test this idea, researchers installed high‑sensitivity microphones on the roofs of several homes and measured pressure fluctuations over weeks. While they did detect occasional low‑frequency spikes, these events were sporadic and did not correlate consistently with the times residents reported hearing the hum.`,
    `Another line of inquiry turned to the possibility of <span class="vocab" data-cn="电磁干扰">electromagnetic interference</span>. Some investigators hypothesized that stray electromagnetic fields from power lines or nearby radio transmitters might induce a sensation of sound within the inner ear, a phenomenon known as the “microwave auditory effect.” Experiments involving shielded rooms and controlled exposure to various frequencies yielded mixed results; a few participants reported phantom sounds, but the majority experienced no perceptible hum. The lack of reproducibility kept this theory on the fringe of mainstream research.`,
    `The Taos hum was not an isolated case. Similar reports emerged from locations as far apart as the United Kingdom’s “Bristol Hum,” Canada’s “Ontario Hum,” and even remote parts of Australia. Comparative studies revealed a striking similarity in the subjective descriptions: a low, steady tone that seemed to emanate from nowhere, often described as “a distant engine idling.” These parallel cases prompted some scientists to propose a global <span class="vocab" data-cn="声学异常">acoustic anomaly</span>, perhaps linked to atmospheric conditions or tectonic activity. However, extensive geophysical surveys—including seismic monitoring and ground‑penetrating radar—failed to uncover any consistent geological source that could account for the widespread reports.`,
    `In recent years, advances in neuroimaging have offered a fresh perspective. Functional MRI scans of individuals who claim to hear the hum show heightened activity in the auditory cortex even when no external sound is present, suggesting that the brain may generate its own “phantom” noise under certain conditions. This aligns with research on tinnitus, where sufferers experience persistent ringing without an external source. Yet, unlike typical tinnitus, the Taos hum often appears only intermittently and can be shared among multiple people in the same environment, complicating a purely neurological explanation.`,
    `To this day, the Taos hum remains an open question—a reminder that our sensory world still holds mysteries beyond current scientific reach. While many hypotheses have been proposed—from industrial machinery vibrations to subtle psychological suggestibility—none have achieved universal acceptance. The phenomenon continues to inspire both rigorous field studies and speculative documentaries, ensuring that the low‑frequency whisper of Taos will keep puzzling scientists and curious minds alike for years to come.`,
  ],
  vocabulary: [
    { word: 'spectral analysis', cn: '声谱分析' },
    { word: 'ambient noise', cn: '环境噪声' },
    { word: 'psychophysiology', cn: '心理生理学' },
    { word: 'infrasound', cn: '次声' },
    { word: 'electromagnetic interference', cn: '电磁干扰' },
    { word: 'acoustic anomaly', cn: '声学异常' },
  ],
};

export default article;
