import type { Article } from '../../types/index.ts';

// 文件意图：维护《The Great Stink of London, 1858: How a River of Sewage Prompted Modern Sanitation》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00136 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00136',
  slug: 'the-great-stink-of-london-1858-how-a-river-of-sewage-prompted-modern-sanitation',
  title: 'The Great Stink of London, 1858: How a River of Sewage Prompted Modern Sanitation',
  subtitle: 'When the Thames turned into an open sewer and forced a city to reinvent its public health system.',
  summary: 'In summer 1858 the foul smell from the polluted Thames halted Parliament and sparked the creation of one of the world’s first modern sewer networks.',
  category: 'history',
  difficulty: 'intermediate',
  readingMinutes: 5,
  paragraphs: [
    `By the mid‑19th century, rapid industrialisation and a booming population had turned London into a sprawling metropolis. The city’s waste—human excrement, industrial effluent, and runoff from streets—was dumped directly into the <span class="vocab" data-cn="伦敦泰晤士河">Thames</span>. As the river widened downstream, its flow slowed, allowing sludge to accumulate in a thick, black layer that emitted a nauseating odor, especially during hot weather.`,
    `The smell reached a climax on a sweltering July day in 1858. Parliament’s chambers, situated beside the river, became almost unbearable as the foul air seeped through open windows. Law‑makers and journalists described it as “a cloud of pestilence” that threatened to choke the nation’s capital. This event quickly earned the nickname “The Great Stink,” and it forced politicians to confront a problem they had long ignored: the city’s inadequate sanitation infrastructure.`,
    `At the time, many still subscribed to the <span class="vocab" data-cn="瘴气说">miasma theory</span>, which held that disease spread through “bad air.” The stench was therefore seen not only as an inconvenience but also as a direct health hazard. Indeed, London had suffered several deadly <span class="vocab" data-cn="霍乱">cholera</span> outbreaks in the previous decades, most famously the 1854 epidemic that claimed thousands of lives. Although the link between contaminated water and cholera was still debated, the Great Stink made it impossible to deny a connection between waste, smell, and illness.`,
    `One of the key figures who helped shift public opinion was <span class="vocab" data-cn="流行病学家">John Snow</span>. By mapping cholera cases around the Broad Street pump, Snow demonstrated that the disease followed water sources rather than airborne particles. His work provided a scientific foundation for engineers to argue that removing sewage from the river would improve public health, even if many officials remained skeptical of his conclusions.`,
    `The political pressure generated by the Great Stink finally convinced the government to act. In 1859, Parliament approved an ambitious plan led by civil engineer <span class="vocab" data-cn="公共卫生工程师">Joseph Bazalgette</span>. He designed a massive <span class="vocab" data-cn="下水道系统">sewer network</span> that would intercept waste before it entered the Thames, channeling it downstream to treatment facilities. The project involved constructing over 80 miles of brick‑lined tunnels, some large enough for a horse-drawn carriage to pass through, and required innovative use of steam-powered pumps to lift sewage over the river’s banks.`,
    `Bazalgette’s design was remarkable not only for its scale but also for its foresight. He built the sewers with a capacity far greater than the city’s current needs, anticipating future growth. This “over‑engineering” proved crucial when London’s population exploded in the following decades; the system continued to function effectively well into the 20th century, dramatically reducing waterborne diseases and setting a global benchmark for urban <span class="vocab" data-cn="防疫措施">sanitation</span>.`,
    `The legacy of the Great Stink extends far beyond Victorian London. It demonstrated how environmental crises can catalyze scientific inquiry, engineering innovation, and political will. Modern cities worldwide still look to Bazalgette’s example when designing resilient water‑management systems, reminding us that a foul river once forced an empire to rethink how it protects its citizens from invisible threats.`,
  ],
  vocabulary: [
    { word: 'Thames', cn: '伦敦泰晤士河' },
    { word: 'Joseph Bazalgette', cn: '公共卫生工程师' },
    { word: 'sewer network', cn: '下水道系统' },
    { word: 'cholera', cn: '霍乱' },
    { word: 'John Snow', cn: '流行病学家' },
    { word: 'sanitation', cn: '防疫措施' },
    { word: 'miasma theory', cn: '瘴气说' },
  ],
};

export default article;
