import type { Article } from '../../types/index.ts';

// 文件意图：维护《Great Zimbabwe: Stone City, Trade Networks, and the Colonial Myth‑Making That Shaped Its Legacy》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00156 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00156',
  slug: 'great-zimbabwe-stone-city-trade-networks-and-the-colonial-myth-making-that-shaped-its-legacy',
  title: 'Great Zimbabwe: Stone City, Trade Networks, and the Colonial Myth‑Making That Shaped Its Legacy',
  subtitle: 'Exploring the rise, commerce, and contested memory of Southern Africa’s most iconic ruins.',
  summary: 'A narrative journey through Great Zimbabwe’s architecture, its far‑reaching trade links, and how colonial narratives reshaped its legacy.',
  category: 'history',
  difficulty: 'intermediate',
  readingMinutes: 6,
  paragraphs: [
    `In the rolling grasslands of present‑day Zimbabwe stand the crumbling walls of <span class="vocab" data-cn="大津巴布韦">Great Zimbabwe</span>, a city whose stone structures rose between the 11th and 15th centuries. Unlike many African settlements that relied on mud or timber, its builders mastered <span class="vocab" data-cn="干砌石技术">dry stone masonry</span>, fitting granite blocks together without mortar to create towering walls, terraces, and the famous conical tower. The sheer scale of these constructions—some walls reaching over ten meters high—testifies to a sophisticated social organization capable of mobilizing labor across vast distances.`,
    `Archaeologists have uncovered evidence that Great Zimbabwe was not an isolated citadel but the hub of an extensive <span class="vocab" data-cn="贸易商队">trade caravan</span> network. Gold, ivory, and iron from the interior were exchanged for glass beads, porcelain, and cloth arriving via Swahili ports on the Indian Ocean coast. Excavated ceramics bearing Chinese porcelain glaze and Arab copperware illustrate how merchants from as far as Guangzhou and Zanzibar reached this inland city, turning it into a vibrant node in the medieval Indian Ocean trade system.`,
    `The wealth generated by these exchanges fostered specialized crafts within the city itself. Artisans practiced <span class="vocab" data-cn="金匠技术">goldsmithing</span>, producing intricate gold ornaments that have been found in burial sites, while others worked as stone carvers, leaving behind soapstone figurines and decorative motifs on wall surfaces. These material cultures reveal a society that valued both economic prosperity and artistic expression, challenging early European assumptions that African societies lacked complexity.`,
    `When Portuguese explorers first sighted the ruins in the 16th century, they recorded their awe but also projected their own worldview onto the site. Colonial scholars later coined the term “<span class="vocab" data-cn="殖民考古学">colonial archaeology</span>” to describe a discipline that sought to explain African achievements through foreign agency. Influential figures such as Carl Peters and Cecil Rhodes promoted an <span class="vocab" data-cn="欧洲中心叙事">Eurocentric narrative</span>, claiming the stone city must have been built by Phoenicians, Arabs, or even lost civilizations of the New World, thereby denying its African origins.`,
    `These myths persisted well into the 20th century, influencing both academic discourse and popular imagination. It was not until the mid‑1900s that scholars like Shadreck Chirikure and Peter Garlake presented robust archaeological evidence—radiocarbon dates, local oral histories in the <span class="vocab" data-cn="绍纳语">Shona language</span>, and stylistic analyses of pottery—that firmly re‑attributed Great Zimbabwe to its indigenous builders. Their work helped dismantle the entrenched myth that Africa could not produce such monumental architecture on its own.`,
    `Today, Great Zimbabwe is a UNESCO World Heritage Site and a focal point for <span class="vocab" data-cn="遗产旅游">heritage tourism</span>. The site draws visitors eager to see the towering walls and learn about the city's past, while also sparking debates over how best to preserve and interpret the ruins. Local communities advocate for narratives that honor their ancestors, whereas some international stakeholders emphasize its role in global trade history. This tension reflects a broader struggle to balance economic development with cultural integrity.`,
    `The legacy of Great Zimbabwe thus rests on three intertwined pillars: architectural ingenuity, expansive commercial networks, and the contested stories told about it. By recognizing the city's African agency, acknowledging its place within a worldwide exchange system, and critically examining the colonial myths that once obscured its true origins, we gain a fuller appreciation of how past societies shaped—and were shaped by—their world. The stone walls still stand as silent witnesses to a vibrant civilization whose memory continues to evolve.`,
  ],
  vocabulary: [
    { word: 'Great Zimbabwe', cn: '大津巴布韦' },
    { word: 'dry stone masonry', cn: '干砌石技术' },
    { word: 'trade caravan', cn: '贸易商队' },
    { word: 'goldsmithing', cn: '金匠技术' },
    { word: 'colonial archaeology', cn: '殖民考古学' },
    { word: 'Eurocentric narrative', cn: '欧洲中心叙事' },
    { word: 'Shona language', cn: '绍纳语' },
    { word: 'heritage tourism', cn: '遗产旅游' },
  ],
};

export default article;
