import type { Article } from '../../types/index.ts';

// 文件意图：维护《Stealth in the Skies: The Development and Secrets of Lockheed’s Have Blue Prototype》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00174 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00174',
  slug: 'stealth-in-the-skies-the-development-and-secrets-of-lockheed-s-have-blue-prototype',
  title: 'Stealth in the Skies: The Development and Secrets of Lockheed’s Have Blue Prototype',
  subtitle: 'How a hidden testbed paved the way for modern low‑observable fighters',
  summary: 'An inside look at the secretive Have Blue program that proved key stealth concepts for later aircraft.',
  category: 'technology',
  difficulty: 'advanced',
  readingMinutes: 6,
  paragraphs: [
    `In the late 1970s, as the Cold War intensified, the United States sought a way to evade increasingly sophisticated Soviet radar. The answer lay in <span class="vocab" data-cn="隐身">stealth</span> technology—a radical departure from traditional aircraft design. While the F‑117 Nighthawk had already demonstrated that a faceted shape could reduce detection, engineers at Lockheed’s Skunk Works were tasked with proving whether an even more advanced prototype could be built without attracting attention. The result was <strong>Have Blue</strong>, a secret testbed whose very existence remained classified for years.`,
    `The program began under the leadership of Ben Rich, who inherited the “black” projects from Kelly Johnson. Rich’s team focused on creating a truly <span class="vocab" data-cn="低可观测">low‑observable</span> airframe that could survive high‑speed flight while maintaining a minimal <span class="vocab" data-cn="雷达散射截面">radar cross‑section</span>. To achieve this, they abandoned conventional aerodynamic curves in favor of sharp angles—a design philosophy known as “faceting.” Each flat surface was carefully angled to reflect incoming radar waves away from the source, rather than back toward it.`,
    `Materials played an equally crucial role. The prototype’s skin combined aluminum alloys with emerging <span class="vocab" data-cn="复合材料">composite materials</span>, which offered both structural strength and radar‑absorbing properties. Special coatings infused with iron ferrite particles were applied to further dampen reflected signals. These innovations meant that, on a ground‑based radar sweep, Have Blue appeared as nothing more than a faint blip—if it was detected at all.`,
    `Testing took place at the remote Groom Lake facility, better known as Area 51. Only a handful of specially trained pilots were allowed to fly the aircraft, and they relied on an advanced <span class="vocab" data-cn="电传操纵系统">fly‑by‑wire</span> system. Because the faceted shape compromised natural stability, computer‑controlled surfaces constantly adjusted the plane’s attitude, keeping it level without the pilot needing to make large manual inputs. The secrecy surrounding these flights was so strict that even senior officials were unaware of the program’s progress until after its successful conclusion.`,
    `Despite its successes, Have Blue faced numerous technical hurdles. Managing heat generated by the engines proved difficult because traditional cooling ducts would have increased the aircraft’s radar signature. Engineers therefore devised internal airflow channels that concealed heat exchangers behind the aircraft’s skin. Integrating modern avionics while preserving stealth characteristics also required innovative shielding techniques to prevent electronic emissions from betraying the plane’s position.`,
    `When the prototype finally demonstrated consistent low‑observable performance, the data gathered fed directly into the development of the F‑22 Raptor and later the B‑2 Spirit bomber. Although Have Blue never entered production itself, its flight test results validated the core principles of modern stealth design—principles that continue to shape fifth‑generation fighters today. The program was officially declassified in the early 1990s, allowing historians to piece together its remarkable story.`,
    `The legacy of Have Blue extends beyond aircraft shapes. Contemporary research now targets the broader <span class="vocab" data-cn="电磁特征">electromagnetic signature</span> of platforms, including infrared and acoustic emissions. By combining advanced shaping with active cancellation techniques, engineers aim to create vehicles that are virtually invisible across multiple detection spectra. In this way, the quiet success of a hidden prototype from over four decades ago still echoes in today’s cutting‑edge defense technologies.`,
  ],
  vocabulary: [
    { word: 'stealth', cn: '隐身' },
    { word: 'radar cross-section', cn: '雷达散射截面' },
    { word: 'composite materials', cn: '复合材料' },
    { word: 'fly-by-wire', cn: '电传操纵系统' },
    { word: 'low-observable', cn: '低可观测' },
    { word: 'electromagnetic signature', cn: '电磁特征' },
  ],
};

export default article;
