import type { Article } from '../../types/index.ts';

// 文件意图：维护《The Lituya Bay Megatsunami of 1958: The World's Largest Wave and Its Scientific Legacy》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00291 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00291',
  slug: 'the-lituya-bay-megatsunami-of-1958-the-world-s-largest-wave-and-its-scientific-legacy',
  title: 'The Lituya Bay Megatsunami of 1958: The World\'s Largest Wave and Its Scientific Legacy',
  subtitle: 'How a sudden landslide created an unprecedented wave and reshaped coastal science.',
  summary: 'A dramatic account of the 1958 Lituya Bay megatsunami, its causes, impacts, and lasting influence on tsunami research.',
  category: 'science',
  difficulty: 'intermediate',
  readingMinutes: 5,
  paragraphs: [
    `On July 9, 1958, a massive <span class="vocab" data-cn="巨型海啸">megatsunami</span> surged through Lituya Bay in southeastern Alaska, carving a vertical scar up to 524 meters (1,720 feet) into the ancient spruce forest. The wave was not generated by an earthquake but by a sudden collapse of about 30 million cubic meters of rock and ice from the surrounding slopes, a phenomenon that still astonishes geologists today.`,
    `The trigger was a magnitude‑7.8 <span class="vocab" data-cn="地震">earthquake</span> along the Fairweather Fault, part of the larger Pacific‑North American <span class="vocab" data-cn="俯冲带">subduction zone</span>. The seismic shaking destabilized a massive glacially carved wall at the head of the bay, causing it to fail catastrophically. When the rock‑ice mass plunged into the water, it displaced an estimated 30 cubic kilometers of seawater in a fraction of a second, creating a towering wave that raced across the narrow inlet.`,
    `Lituya Bay’s unique geography amplified the disaster. The bay is a steep, fjord‑like basin surrounded by towering peaks and capped by a tidewater glacier. Its shallow <span class="vocab" data-cn="海底地形">bathymetry</span> meant that the displaced water could not spread outward easily; instead it surged upward along the shoreline, producing an extreme <span class="vocab" data-cn="波浪最高点">run‑up height</span>. The wave’s energy was further focused by a narrow entrance, turning the entire bay into a giant hydraulic piston.`,
    `The human toll, while relatively low, underscored the event’s power. Two fishing boats were caught in the surge; one, the <em>Badger</em>, capsized and left its crew stranded on a floating platform for over an hour before rescue arrived. Remarkably, only three of the 31 people aboard perished, largely because many vessels were anchored well outside the bay’s mouth when the wave struck. Their survival stories have become classic case studies in emergency response and disaster psychology.`,
    `Scientists rushed to document the aftermath. Survey teams measured the stripped trees, noting that trunks up to 30 centimeters in diameter had been sheared cleanly at the base. The vertical scar left on the forest provided a rare, direct measurement of wave energy conversion from landslide to water motion. These observations helped refine mathematical models of <span class="vocab" data-cn="海啸波动">tsunami dynamics</span>, especially for events where the source is a rapid mass displacement rather than tectonic uplift.`,
    `In the decades that followed, Lituya Bay became a natural laboratory for studying extreme coastal hazards. Researchers used high‑resolution satellite imagery and LiDAR scans to reconstruct the pre‑event topography, allowing them to simulate the landslide with modern computational fluid dynamics (CFD) tools. The simulations confirmed that the wave’s height was largely controlled by the volume of the slide and the confined geometry of the bay, insights that have been applied to risk assessments in other fjord regions worldwide.`,
    `The legacy of the 1958 megatsunami extends beyond academic circles. Coastal planners now incorporate scenarios of landslide‑generated waves when designing early warning systems for vulnerable communities, especially in glaciated mountain coasts such as Chile, Norway, and New Zealand. Moreover, the event sparked interdisciplinary collaborations between geologists, oceanographers, and engineers, fostering a holistic approach to hazard mitigation that continues to evolve with advances in remote sensing and real‑time monitoring technologies.`,
  ],
  vocabulary: [
    { word: 'megatsunami', cn: '巨型海啸' },
    { word: 'earthquake', cn: '地震' },
    { word: 'subduction zone', cn: '俯冲带' },
    { word: 'bathymetry', cn: '海底地形' },
    { word: 'run-up height', cn: '波浪最高点' },
    { word: 'tsunami dynamics', cn: '海啸波动' },
  ],
};

export default article;
