import type { Article } from '../../types/index.ts';

// 文件意图：维护《The Development of the Moog Synthesizer and Its Revolution of Music Production》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00313 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00313',
  slug: 'the-development-of-the-moog-synthesizer-and-its-revolution-of-music-production',
  title: 'The Development of the Moog Synthizer and Its Revolution of Music Production',
  subtitle: 'How a humble laboratory turned into a studio staple',
  summary: 'From Robert Moog’s garage experiments to the iconic Minimoog, discover how a single instrument reshaped modern music.',
  category: 'technology',
  difficulty: 'intermediate',
  readingMinutes: 6,
  paragraphs: [
    `In the early 1960s, a young electrical engineer named Robert Moog was tinkering in his New York City apartment, fascinated by the idea of generating sound with pure electricity. His first breakthrough came when he built a simple oscillator that could be tuned by adjusting a voltage—a concept later known as a <span class="vocab" data-cn="电压控制振荡器">voltage-controlled oscillator</span>. This device turned abstract waveforms into musical tones, laying the groundwork for what would become the first commercially viable synthesizer.`,
    `Moog’s next step was to connect several of these oscillators together with a series of modules that could shape and filter the raw signal. He introduced the <span class="vocab" data-cn="滤波截止频率">filter cutoff</span> control, allowing musicians to sweep frequencies in real time, and an <span class="vocab" data-cn="包络发生器">envelope generator</span> that defined how a note’s amplitude changed from attack to release. By arranging these modules on a rack and linking them with flexible cords—later called <span class="vocab" data-cn="补丁线">patch cables</span>—the system became a modular playground for sound designers.`,
    `While the original modular units were powerful, they were also massive and required a deep understanding of electronics. In 1970 Moog released the Minimoog, a compact, portable version that integrated the essential modules onto a single wooden chassis. The instrument featured three <span class="vocab" data-cn="电压控制振荡器">voltage-controlled oscillators</span>, a resonant low‑pass filter, and a built‑in keyboard—everything a performer needed to play synth lines live without a wall of patch cables. Its intuitive front panel made it accessible to musicians who had never touched a circuit board before.`,
    `The Minimoog’s sound was defined by its warm <span class="vocab" data-cn="模拟电路">analog circuitry</span> and the technique known as <span class="vocab" data-cn="减法合成">subtractive synthesis</span>. In this process, rich harmonic content generated by the oscillators is sculpted by filters and envelopes, removing frequencies rather than adding them. This approach produced a thick, organic timbre that digital devices of the era could not replicate. Moog also improved stability by introducing temperature‑compensated components, ensuring that notes stayed in tune even during long performances.`,
    `The impact on music production was immediate and profound. Classical pianist Wendy Carlos used the original modular system to record “Switched-On Bach,” an album that won three Grammy Awards and proved that electronic instruments could be taken seriously by mainstream audiences. Rock groups like Pink Floyd incorporated the Minimoog’s soaring leads into albums such as “The Dark Side of the Moon,” while German pioneers Kraftwerk built entire tracks around its rhythmic bass lines. These artists demonstrated that synthesizers could replace, augment, or inspire traditional instrumentation in ways previously unimaginable.`,
    `Beyond artistic expression, Moog changed how studios operated. Before synthesizers, producers relied on tape splicing and overdubbing to create layered sounds—a time‑consuming process prone to errors. With a Minimoog at the console, engineers could record entire passages in a single take, adjusting parameters on the fly. This real‑time control streamlined workflow, reduced production costs, and opened the door for experimental recording techniques that became hallmarks of 1970s and 1980s pop music.`,
    `Today, the legacy of Moog lives on both in vintage hardware and modern software emulations. The resurgence of analog gear in the 2000s sparked renewed interest in the tactile experience of turning knobs and plugging <span class="vocab" data-cn="补丁线">patch cables</span> together. Contemporary manufacturers often cite Moog’s design philosophy when developing new instruments, and digital synthesizers still emulate its classic filter curves and oscillator behavior. In this way, a modest laboratory invention from the 1960s continues to shape the sound of tomorrow.`,
  ],
  vocabulary: [
    { word: 'voltage-controlled oscillator', cn: '电压控制振荡器' },
    { word: 'filter cutoff', cn: '滤波截止频率' },
    { word: 'envelope generator', cn: '包络发生器' },
    { word: 'patch cable', cn: '补丁线' },
    { word: 'analog circuitry', cn: '模拟电路' },
    { word: 'subtractive synthesis', cn: '减法合成' },
  ],
};

export default article;
