import type { Article } from '../../types/index.ts';

// 文件意图：维护《IKAROS and the Dawn of Solar Sailing: From Theory to Spacecraft》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00356 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00356',
  slug: 'ikaros-and-the-dawn-of-solar-sailing-from-theory-to-spacecraft',
  title: 'IKAROS and the Dawn of Solar Sailing',
  subtitle: 'How sunlight became a practical means of propelling spacecraft',
  summary: 'A narrative tracing solar sailing from early theory to Japan’s IKAROS mission.',
  category: 'technology',
  difficulty: 'advanced',
  readingMinutes: 6,
  paragraphs: [
    `Long before rockets roared, visionary scientists such as Johannes Kepler imagined that sunlight could push objects through space. In the 17th century he noted that comet tails always pointed away from the Sun, hinting at a subtle force. Centuries later, physicists quantified this effect as <span class="vocab" data-cn="光子压力">photon pressure</span>, the tiny thrust generated when photons transfer momentum to a surface. Though minuscule, the force never runs out, making it an attractive candidate for deep‑space propulsion.`,
    `The physics is elegantly simple: each photon carries energy \\(E = h\\nu\\) and momentum \\(p = E/c\\). When a photon strikes a reflective surface, its direction changes, imparting twice its momentum to the material. Over a large area, these infinitesimal pushes add up to a measurable thrust known as <span class="vocab" data-cn="太阳帆">solar sail</span> pressure. For a perfectly reflecting sheet 100 meters on a side at Earth's distance from the Sun, the resulting force is roughly 9 mN—tiny, yet sufficient to accelerate a lightweight spacecraft over months or years.`,
    `Turning theory into practice required overcoming daunting engineering hurdles. The most critical was finding a material that combined extreme lightness with high reflectivity and durability against micrometeoroids and ultraviolet radiation. Researchers settled on <span class="vocab" data-cn="薄膜聚合物">thin‑film polymer</span> membranes coated with aluminum, achieving areal densities as low as 10 g/m². Equally challenging was designing a reliable <span class="vocab" data-cn="可展开结构">deployable structure</span> that could be stowed compactly during launch and then unfurl to its full span in the vacuum of space without tearing or snagging.`,
    `Japan’s Aerospace Exploration Agency (JAXA) took the bold step of testing these ideas with IKAROS (Interplanetary Kite‑crafT Accelerated by Radiation Of the Sun), launched on 21 May 2010. The spacecraft carried a square sail measuring 20 m per side, made of the aforementioned thin‑film polymer. After a brief coast, the sail was released and unfurled using centrifugal force generated by the spin of the bus. Sensors confirmed that the deployment succeeded within minutes, marking the first time a solar sail had been operated beyond Earth orbit.`,
    `IKAROS also pioneered an innovative method of <span class="vocab" data-cn="姿态控制">attitude control</span> without conventional thrusters. Embedded along the sail were 25 µm‑thick liquid crystal panels that could change their optical properties on command, altering local photon pressure to produce torque. By selectively dimming or brightening these patches, the spacecraft could rotate itself, maintain orientation toward the Sun, and even execute modest trajectory corrections—all while conserving propellant.`,
    `During its 1‑year cruise to Venus, IKAROS demonstrated that solar radiation pressure could indeed modify a <span class="vocab" data-cn="日心轨道">heliocentric orbit</span>. The sail’s thrust gradually raised the spacecraft’s orbital energy, allowing it to perform a successful flyby of Venus in June 2010 and later return to an Earth‑crossing trajectory. Scientific instruments measured the pressure with unprecedented accuracy, confirming theoretical predictions and providing valuable data for future missions such as Planetary Society’s LightSail 2 and NASA’s upcoming NEA Scout, which will rely on similar principles for asteroid exploration.`,
    `IKAROS’ success ignited a renaissance in solar sailing research worldwide. Engineers are now designing sails tens of meters across, envisioning <span class="vocab" data-cn="星际任务">interplanetary missions</span> that could reach the outer planets in a fraction of the time required by chemical propulsion. Concepts like NASA’s Solar Cruiser and ESA’s Gossamer‑1 aim to test larger membranes and advanced navigation techniques. While ambitious projects such as Breakthrough Starshot explore laser‑driven sails, the fundamental lesson remains: sunlight, though gentle, can be harnessed as a reliable and inexhaustible means of space travel.`,
  ],
  vocabulary: [
    { word: 'photon pressure', cn: '光子压力' },
    { word: 'solar sail', cn: '太阳帆' },
    { word: 'thin‑film polymer', cn: '薄膜聚合物' },
    { word: 'deployable structure', cn: '可展开结构' },
    { word: 'attitude control', cn: '姿态控制' },
    { word: 'heliocentric orbit', cn: '日心轨道' },
    { word: 'interplanetary mission', cn: '星际任务' },
  ],
};

export default article;
