import type { Article } from '../../types/index.ts';

// 文件意图：维护《The Secret Race to Build the First Practical Steam‑Powered Submarine: Narcís Monturiol’s Ictineo II》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00465 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00465',
  slug: 'the-secret-race-to-build-the-first-practical-steam-powered-submarine-narc-s-monturiol-s-ictineo-ii',
  title: 'The Secret Race to Build the First Practical Steam‑Powered Submarine: Narcís Monturiol’s Ictineo II',
  subtitle: 'How a Catalan inventor hid his daring experiments from the eyes of Europe’s navies.',
  summary: 'A narrative of Monturiol’s clandestine engineering feat that pushed steam power beneath the waves for the first time.',
  category: 'technology',
  difficulty: 'intermediate',
  readingMinutes: 6,
  paragraphs: [
    `In the early 1860s, a quiet competition simmered beneath the surface of Europe’s great seas. While Britain and France were busy perfecting ironclads, a handful of visionary engineers whispered about vessels that could disappear below water and reappear at will. Among them was Catalan inventor <span class="vocab" data-cn="纳西斯·蒙图里奥尔">Narcís Monturiol</span>, whose ambition to build a truly <span class="vocab" data-cn="蒸汽动力的">steam‑powered</span> submarine placed him at the heart of this secret race.`,
    `Monturiol’s fascination with underwater travel began long before his famous Ictineo II. In 1859 he launched the modest <span class="vocab" data-cn="伊克蒂内奥一号">Ictineo I</span>, a hand‑cranked craft designed to rescue miners trapped after a flood in Catalonia’s coal mines. The experience taught him that human power alone could not sustain long submersions, and he turned his attention to the industrial marvel of his age: the steam engine. His goal was audacious—to harness steam while keeping the vessel sealed from the crushing sea pressure.`,
    `Marrying steam with submersion presented a series of engineering riddles that had never been solved. A conventional boiler required an open fire and abundant oxygen, both impossible inside a watertight hull. Monturiol responded by inventing a closed‑cycle system in which coal was burned in a sealed furnace, and the resulting heat was transferred to water via a series of <span class="vocab" data-cn="液压泵">hydraulic pumps</span> that drove the propeller without exposing the engine to seawater. He also devised an early <span class="vocab" data-cn="氧气清除装置">oxygen scrubber</span>, using lime to absorb carbon dioxide and extend the crew’s breathable air supply.`,
    `All of this work unfolded in a modest shipyard on Barcelona’s waterfront, hidden behind false walls and guarded by trusted workers. The hull was constructed from wrought iron plates riveted together, creating a pressure‑resistant shell that could be flooded and emptied through cleverly designed <span class="vocab" data-cn="压舱水箱">ballast tanks</span>. Monturiol’s notebooks reveal that he timed each ballast operation with the rhythm of his steam engine, allowing the submarine to dive smoothly and surface on command. The secrecy was not merely technical; Spain’s political climate under Queen Isabella II made any independent military innovation a potential target for censorship or confiscation.`,
    `On August 20, 1864, Monturiol finally slipped Ictineo II beneath the waves of the Mediterranean for its inaugural dive. The craft, measuring roughly eight meters in length and displacing about twelve tons, descended to a depth of ten meters while maintaining a steady speed of three knots. Observers on the deck reported that the steam engine ran quietly, a stark contrast to the clanking pistons of surface vessels. However, the trial also exposed flaws: the heat generated by the furnace raised internal temperatures uncomfortably high, and the lime‑based scrubber struggled after prolonged submersion, forcing Monturiol to abort the dive after thirty minutes.`,
    `Despite these setbacks, Ictineo II left an indelible mark on naval engineering. Its combination of a sealed steam cycle, ballast control, and air purification prefigured later designs such as the French <span class="vocab" data-cn="潜水艇">Plongeur</span> (1872) and even influenced the early German <span class="vocab" data-cn="U‑boat">U‑boat</span> concepts of the 20th century. Monturiol’s willingness to experiment with closed‑cycle propulsion demonstrated that submarines could be more than short, hand‑cranked toys; they could become practical tools for warfare and rescue alike. Yet his work remained largely unknown outside Spain, partly because he lacked state funding and partly because his inventions were shrouded in the very secrecy that had protected them.`,
    `Today, Monturiol’s legacy resurfaces whenever historians recount the hidden chapters of underwater technology. The Ictineo II stands as a testament to what can be achieved when imagination confronts the limits of contemporary science, and it reminds us that many breakthroughs begin not on grand battlefields but in quiet workshops where inventors dare to dream beneath the waves.`,
  ],
  vocabulary: [
    { word: 'Narcís Monturiol', cn: '纳西斯·蒙图里奥尔' },
    { word: 'steam‑powered', cn: '蒸汽动力的' },
    { word: 'Ictineo I', cn: '伊克蒂内奥一号' },
    { word: 'hydraulic pump', cn: '液压泵' },
    { word: 'oxygen scrubber', cn: '氧气清除装置' },
    { word: 'ballast tanks', cn: '压舱水箱' },
    { word: 'Plongeur', cn: '潜水艇（法国的“潜航者”）' },
    { word: 'U‑boat', cn: 'U型潜艇（德国）' },
  ],
};

export default article;
