import type { Article } from '../../types/index.ts';

// 文件意图：维护《The Construction of the Hoover Dam: Engineering Triumph, Politics, and Human Cost》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00471 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00471',
  slug: 'the-construction-of-the-hoover-dam-engineering-triumph-politics-and-human-cost',
  title: 'The Construction of the Hoover Dam: Engineering Triumph, Politics, and Human Cost',
  subtitle: 'How a massive public works project reshaped the American West.',
  summary: 'An engaging look at the engineering feats, political battles, and human stories behind the Hoover Dam.',
  category: 'history',
  difficulty: 'advanced',
  readingMinutes: 6,
  paragraphs: [
    `In the early 1930s, as the Great Depression deepened, the United States faced a paradoxical shortage of both water and electricity in its arid Southwest. The federal government saw an opportunity to stimulate the economy while solving two pressing problems, and the project was placed under the authority of the <span class="vocab" data-cn="美国垦务局">Bureau of Reclamation</span>. Yet before any concrete could be poured, a fierce political tug‑of‑war erupted between California, which wanted unlimited water rights, and Arizona, which feared being left dry. This clash set the stage for one of the most ambitious public works endeavors in American history.`,
    `The chosen design was nothing short of revolutionary: an <span class="vocab" data-cn="拱重力坝">arch‑gravity dam</span> that would combine the strength of a traditional gravity dam with the elegance of an arch, allowing it to transfer water pressure into the surrounding rock. Engineers divided the massive structure into hundreds of <span class="vocab" data-cn="混凝土整体块体">concrete monoliths</span>, each poured in stages and allowed to cure before the next was added. This modular approach not only facilitated construction on a previously unimaginable scale but also helped manage the heat generated by the chemical reaction of cement, preventing cracks that could jeopardize the dam’s integrity.`,
    `Building the dam required an arsenal of innovative techniques. Workers employed massive <span class="vocab" data-cn="爆破作业">blasting</span> charges to carve tunnels through the canyon walls, creating pathways for both water and construction crews. Gigantic cableways stretched across the Colorado River, ferrying men, equipment, and concrete buckets with astonishing precision. Meanwhile, a network of cooling towers sprayed water on fresh concrete to control temperature, a practice that would later become standard in large‑scale dam projects worldwide.`,
    `The human story behind the engineering marvel is both inspiring and tragic. Over 5,000 laborers—many of them recent immigrants and members of <span class="vocab" data-cn="工会劳工">union labor</span>—toiled under scorching heat in summer and bitter cold in winter. Safety standards were rudimentary; workers faced hazards such as falling rocks, high‑pressure steam, and the ever‑present risk of drowning while working in cofferdams. By the time construction ended, more than 100 men had lost their lives, a sobering reminder that progress often comes at a steep human cost.`,
    `Politically, the dam’s completion was a triumph for federal authority. The project secured funding through the Emergency Relief Appropriation Act and helped solidify the <span class="vocab" data-cn="水电能源">hydroelectric power</span> paradigm that would electrify cities from Los Angeles to Phoenix. Moreover, the dam became a cornerstone of the Colorado River Compact, an agreement that allocated water among seven basin states and shaped regional development for decades. The political compromises made during its planning still influence water policy in the West today.`,
    `When the gates finally opened in 1936, the reservoir—later named Lake Mead—filled behind the towering concrete wall, submerging the once‑rugged <span class="vocab" data-cn="峡谷壁">canyon walls</span> of Black Canyon. The dam’s turbines began generating electricity at a capacity of over 2,000 megawatts, enough to power millions of homes and spur industrial growth throughout the Southwest. Its presence also created new recreational opportunities, turning the area into a popular destination for boating, fishing, and tourism.`,
    `Today, the Hoover Dam stands as a testament to human ingenuity, political will, and the sacrifices of countless workers. Modern engineers study its design to understand how early 20th‑century technology tackled challenges that still confront dam builders today—such as seismic resilience and environmental impact. As climate change reshapes water availability in the West, the lessons learned from the Hoover Dam’s construction remind us that large‑scale infrastructure must balance ambition with responsibility, lest we repeat the costly mistakes of the past.`,
  ],
  vocabulary: [
    { word: 'Bureau of Reclamation', cn: '美国垦务局' },
    { word: 'arch-gravity dam', cn: '拱重力坝' },
    { word: 'concrete monoliths', cn: '混凝土整体块体' },
    { word: 'blasting', cn: '爆破作业' },
    { word: 'union labor', cn: '工会劳工' },
    { word: 'hydroelectric power', cn: '水电能源' },
    { word: 'canyon walls', cn: '峡谷壁' },
  ],
};

export default article;
