import type { Article } from '../../types/index.ts';

// 文件意图：维护《Project Gemini IV: Ed White’s First American Spacewalk and the Unexpected Perils of Zero‑Gravity》这篇文章的完整内容，供文章自动索引入口读取。
// 维护重点：只改本文内容；文章顺序由文件名前缀 00496 控制，不要手写上一篇/下一篇。
const article: Article = {
  id: '00496',
  slug: 'project-gemini-iv-ed-white-s-first-american-spacewalk-and-the-unexpected-perils-of-zero-gravity',
  title: 'Project Gemini IV: Ed White’s First American Spacewalk and the Unexpected Perils of Zero‑Gravity',
  subtitle: 'How a daring EVA reshaped America\'s approach to spaceflight.',
  summary: 'Ed White stepped into the void on Gemini IV, revealing both triumph and hidden dangers of working in microgravity.',
  category: 'history',
  difficulty: 'intermediate',
  readingMinutes: 6,
  paragraphs: [
    `On June 3 1965, NASA launched Gemini IV from Cape Cape Canaveral atop a Titan II rocket. The two‑man crew—pilot James A. McDivitt and command pilot Ed White—were tasked with testing the limits of human endurance in orbit. While McDivitt piloted the capsule, White prepared for what would become the first United States <span class="vocab" data-cn="舱外活动">extravehicular activity</span> (EVA). The mission’s primary goal was to see whether a astronaut could work outside a spacecraft without losing control of the vehicle, a question that had profound implications for future lunar missions.`,
    `White suited up in a specially designed <span class="vocab" data-cn="加压服">pressurized suit</span> that supplied oxygen and removed carbon dioxide. The suit’s layers included an outer thermal blanket to protect against extreme temperature swings, and a rigid helmet with a gold‑coated visor for radiation shielding. After sealing the spacecraft’s rear hatch, the crew opened the airlock—a small compartment that could be depressurized without compromising the main cabin. As the pressure equalized with space, White floated toward the open hatch, tethered to the capsule by a 25‑meter cord that would later prove both a lifeline and a source of anxiety.`,
    `When White finally stepped into the void, he experienced <span class="vocab" data-cn="微重力">microgravity</span> in its purest form. Without gravity pulling him down, his movements were slow and deliberate; every push sent him gliding across the blackness like a feather on a breeze. The EVA lasted 23 minutes, during which White floated hand‑over‑hand along the capsule’s exterior, testing his suit’s mobility and the functionality of tools designed for space repair. He reported that even simple tasks—such as turning a wrench—required careful planning because any sudden motion could send him spinning away from the spacecraft.`,
    `The seemingly graceful dance quickly revealed hidden perils. As White moved, small debris inside the airlock—loose bolts and a stray screwdriver—began to drift aimlessly, threatening to become hazardous projectiles. More critically, the tether’s tension fluctuated, making it difficult for McDivitt to maintain precise <span class="vocab" data-cn="航天器姿态控制">spacecraft attitude control</span>. The capsule’s reaction wheels, which kept the vehicle oriented, had to compensate for the minute forces generated by White’s pushes. Additionally, prolonged exposure of the suit’s outer layer raised concerns about the <span class="vocab" data-cn="热防护系统">thermal protection system</span>, as direct sunlight could heat parts of the suit far beyond design limits while shadowed sections cooled rapidly.`,
    `Back inside the capsule, McDivitt monitored telemetry and communicated with Mission Control, noting that White’s heart rate spiked whenever he drifted too far from the hatch. The crew’s debrief highlighted the need for a more robust tether system and better methods to secure loose objects before an EVA. These lessons directly influenced Gemini VIII, where astronaut Neil Armstrong performed a longer spacewalk using improved restraints and a redesigned suit that incorporated a built‑in umbilical for power and communications.`,
    `The legacy of Gemini IV extended far beyond the 23 minutes of floating freedom. Engineers applied insights from White’s experience to refine <span class="vocab" data-cn="轨道力学">orbital mechanics</span> calculations, ensuring that future EVAs would not unintentionally alter a spacecraft’s trajectory. The incident also accelerated development of the “Apollo A7L” suit, which featured enhanced mobility joints and a more reliable life‑support system. Public reaction was electrifying; millions watched live television as White floated weightlessly, cementing the image of astronauts as pioneers venturing into an alien environment.`,
    `In retrospect, Ed White’s daring step outside Gemini IV was both a triumph and a cautionary tale. It proved that humans could survive—and work—in the vacuum of space, yet it also exposed subtle dangers such as floating debris, tether dynamics, and thermal stresses that would have to be mastered before setting foot on the Moon. The mission’s unexpected challenges reshaped NASA’s engineering philosophy, emphasizing redundancy, rigorous pre‑EVA checks, and a deeper understanding of how <span class="vocab" data-cn="微重力">microgravity</span> fundamentally alters human interaction with tools and machines. Decades later, every astronaut who steps into the void carries forward the lessons learned on that historic June morning.`,
  ],
  vocabulary: [
    { word: 'extravehicular activity', cn: '舱外活动' },
    { word: 'pressurized suit', cn: '加压服' },
    { word: 'microgravity', cn: '微重力' },
    { word: 'spacecraft attitude control', cn: '航天器姿态控制' },
    { word: 'thermal protection system', cn: '热防护系统' },
    { word: 'orbital mechanics', cn: '轨道力学' },
  ],
};

export default article;
